### John Felix C. Franciso | 2ECE-C

# Programming Assignment 2

## A. Reproducible Normalization Problem

##### Create a reproducible random 5 × 5 integer ndarray named X. Normalize the complete array and store it in the variable "X_normalized." Display X, X normalized, its mean, and its standard deviation.


In [47]:
import numpy as np

np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))

X_normalized = (X - X.mean())/X.std()

print("X =")
print(X)
print("\nX_Normalized =")
print(X_normalized)
print("\nMean = ", round(X_normalized.mean()))
print("\nStandard Deviation =", round(X_normalized.std()))

np.save("X_normalized", X_normalized)

X =
[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

X_Normalized =
[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

Mean =  0

Standard Deviation = 1


## B. Cubes Divisble by 4 Pr

##### Using NumPy, create the first 100 positive integers, cube every element, and reshape the result into a 10 × 10 ndarray named C. Use a Boolean condition on C to obtain every cubed value divisible by 4. Store the selected values in "div_by_4." Preserve NumPy’s normal row-major selection order. Display the shape of C, the array "div_by_4," and the number of selected elements.

In [1]:
import numpy as np

C = np.int64(np.linspace(1, 100, 100))**3
C.resize(10, 10)

div_by_4 = C[(C%4) == 0]
div_by_4

print("C =")
print(C)
print("\nDivisble by 4 =")
print(div_by_4)
print("\nNumber of Selected Elements =", len(div_by_4))

np.save("div_by_4", div_by_4)

C =
[[      1       8      27      64     125     216     343     512     729
     1000]
 [   1331    1728    2197    2744    3375    4096    4913    5832    6859
     8000]
 [   9261   10648   12167   13824   15625   17576   19683   21952   24389
    27000]
 [  29791   32768   35937   39304   42875   46656   50653   54872   59319
    64000]
 [  68921   74088   79507   85184   91125   97336  103823  110592  117649
   125000]
 [ 132651  140608  148877  157464  166375  175616  185193  195112  205379
   216000]
 [ 226981  238328  250047  262144  274625  287496  300763  314432  328509
   343000]
 [ 357911  373248  389017  405224  421875  438976  456533  474552  493039
   512000]
 [ 531441  551368  571787  592704  614125  636056  658503  681472  704969
   729000]
 [ 753571  778688  804357  830584  857375  884736  912673  941192  970299
  1000000]]

Divisble by 4 =
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   3276

## C. Above-Mean Squares Problem 

##### Create a 6 × 6 ndarray named S containing the squares of the first 36 positive integers in increasing row-major order. Compute the mean of all elements of S and store it in S mean. Then use Boolean filtering to select only the elements strictly greater than S mean. Store these values in above mean. Display S, S mean, above mean, and the number of selected elements.

In [49]:
import numpy as np

S = np.int64(np.linspace(1,36,36)**2)
S.resize(6,6)
S_mean = S.mean()
above_mean = S[S>S.mean()]

print("S =")
print(S)
print("\nMean =", S_mean)
print("\nS > Mean =", above_mean)
print("\nNumber of Selected Elements =", len(above_mean))

np.save("above_mean", above_mean)

S =
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

Mean = 450.1666666666667

S > Mean = [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of Selected Elements = 15
